name: Build and release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
      - name: cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('build.gradle.kts') }}
          restore-keys: |
            gradle-${{ hashFiles('build.gradle.kts') }}
            gradle-
      - name: build
        run: ./gradlew build
      - name: get file name
        id: get-filename
        run: echo ::set-output name=filename::$(ls -1 ./build/libs/)
      - name: get version
        id: get-version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: ./gradle.properties
          property: VERSION_NAME
      - name: Release
        uses: Hs1r1us/Release-AIO@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.value }}
          asset_files: ./build/libs/${{ steps.get-filename.outputs.filename }}
  publish:
    name: Publish to maven central
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
      - name: cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('build.gradle.kts') }}
          restore-keys: |
            gradle-${{ hashFiles('build.gradle.kts') }}
            gradle-
      - name: Gradle publish
        run: ./gradlew publish --stacktrace
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}
      - name: Nexus release
        uses: Propromp/nexus-release@1
        with:
          groupId: "net.propromp"
          nexusUsername: ${{ secrets.NEXUS_USERNAME }}
          nexusPassword: ${{ secrets.NEXUS_PASSWORD }}