name: Build and release

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
      - name: cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('build.gradle.kts') }}
          restore-keys: |
            gradle-${{ hashFiles('build.gradle.kts') }}
            gradle-
      - name: build
        run: ./gradlew build
      - name: get file name
        id: get-filename
        run: echo ::set-output name=filename::$(ls -1 ./build/libs/)
      - name: get version
        id: get-version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: ./gradle.properties
          property: VERSION_NAME
      - name: Release
        uses: Hs1r1us/Release-AIO@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.value }}
          asset_files: ./build/libs/${{ steps.get-filename.outputs.filename }}
      - name: import gpg key
        run: |
          export GPG_TTY=$(tty)
          echo -n "$BASE64" | base64 --decode > ./key
          gpg --import ./key
        env:
          BASE64: ${{ secrets.NEXUS_KEY_SECRET_BASE64 }}
      - name: configure publish
        run: |
          echo signing.keyId=${{ secrets.NEXUS_KEY_ID }} >> gradle.properties
          echo signing.password=${{ secrets.NEXUS_KEY_PASSWORD }} >> gradle.properties
          echo mavenCentralUsername=${{ secrets.NEXUS_USERNAME }} >> gradle.properties
          echo mavenCentralPassword=${{ secrets.NEXUS_PASSWORD }} >> gradle.properties
      - name: Gradle publish
        run: ./gradlew publish
      - name: Nexus release
        uses: Propromp/nexus-release@1
        with:
          groupId: "net.propromp"
          nexusUsername: ${{ secrets.NEXUS_USERNAME }}
          nexusPassword: ${{ secrets.NEXUS_PASSWORD }}